### ISSUE TITLE
Write a LaTeX Pandoc template for better PDF output

### ISSUE THREAD

**Issue by jchiquet** [computorg/computo-quarto-extension#2]
For the moment, we manage at least the PDF output, HTML being the preferred output. You have to take the time to make a nice formatting via the LaTeX template for Pandoc

**Comment by fradav** [comment]
There are already a lot of template skeleton in the original upstream https://github.com/quarto-journals/article-format-template/tree/main/_extensions/aft/partials, perhaps we should look there.
