### ISSUE TITLE
tikz rendered with knitr is broken in html output (but webshotted correctly in pdf)

### ISSUE THREAD

**Issue by durandg12** [computorg/computo-quarto-extension#24]
Similar to #21 but for Figure 5 (tikz)

**Comment by durandg12** [comment]
On the submission that I am preparing it is even worse, it is totally broken in html rendering. The caption of the Figure is not rendered, contrary to the template https://computo.sfds.asso.fr/computo-quarto-extension/#diagrams, **and so everything I type after that in my .qmd file, no matter where in the body**

This bug is rather impacting.

**Comment by jchiquet** [comment]
We decided to remove this functionality. TiKZ will not be supported in our template.
Please use tools supported by the quarto team like [mermaid](https://quarto.org/docs/authoring/diagrams.html)

**Comment by fradav** [comment]
workaround found, see #20

**Comment by durandg12** [comment]
Will tikz remain supported thanks to the workaround, or will it still be removed and so I should move on from tikz and follow the recommendations from https://github.com/computorg/computo-quarto-extension/issues/24#issuecomment-2310045430 ?

**Comment by fradav** [comment]
At first I thought I'd leave it up to the authors to generate tikz outputs by themselves, but I changed my mind after a few exchanges with one. Sometimes for some of them, it will be overhead to put a latex/dvisgm/pdf2svg pipeline just for a few tikz schemas, so here we are.

**Comment by durandg12** [comment]
I didn't understand your answer, sorry. Can I continue to use tikz support or will it be dropped?

**Comment by jchiquet** [comment]
Yes, you can count on Tikz support.

**Comment by durandg12** [comment]
Awesome, thanks. I will try again with the new workaround and version of the extension as soon as I have the time
