### ISSUE TITLE
Empty proof block makes the build-deploy github action fail

### ISSUE THREAD

**Issue by durandg12** [computorg/computo-quarto-extension#26]
Maybe this behavior should not appear, or at least it should be documented for the authors that start with writing some paper skeleton and leave some environments empty. It just happened to me and took 30 minutes to find the cause.

```
::: {.proof}

:::
```
inside the .qmd file makes the build-deploy github action fail with this message error : 
<img width="848" alt="Capture d’écran 2024-07-05 à 20 39 07" src="https://github.com/computorg/computo-quarto-extension/assets/45902885/02b57f6d-8485-44bc-905b-1440d31c42a0">

but with
```
::: {.proof}

Content
:::
```
everything is ok.

**Comment by fradav** [comment]
fixed in 1.6.*
https://github.com/quarto-dev/quarto-cli/issues/10624
