### ISSUE TITLE
Preferably use quarto actions to publish when they work 

### ISSUE THREAD

**Issue by jchiquet** [computorg/computo-quarto-extension#3]
The rendering is currently done with a call to 'quarto render' via bash, the quarto publish action not working with conda. An [issue](https://github.com/quarto-dev/quarto-actions/issues/47) has been filed about this. It seems that the compilation is a bit faster by this way, so we would have to gain.

**Comment by fradav** [comment]
I don’t think not using their official actions is really an issue : ATM their actions are just barebone (they’re just calls to "render/publish") and lack a lot of options.

I don’t understand what do you mean by "compilation is a bit faster", actions can’t speedup compilations, they’re just javascript scripts executed inside a VM.

We could preload the conda env as a pre-render project script, but it will need another action script for that: not worth the hassle, IMHO.

**Comment by jchiquet** [comment]
> I don’t think not using their official actions is really an issue : ATM their actions are just barebone (they’re just calls to "render/publish") and lack a lot of options.

Ok, but in the end, we could expect them having more comprehensive actions, and it is also a way to support them. Anyway, ok to use our own actions.

> I don’t understand what do you mean by "compilation is a bit faster", actions can’t speedup compilations, they’re just javascript scripts executed inside a VM.

It was probably due to the use of pip in place of conda.

> We could preload the conda env as a pre-render project script, but it will need another action script for that: not worth the hassle, IMHO.

Ok, agree with that. But an example with the possibility of caching the conda-env would be nice. What do you think?

**Comment by fradav** [comment]
> > I don’t think not using their official actions is really an issue : ATM their actions are just barebone (they’re just calls to "render/publish") and lack a lot of options.
> 
> Ok, but in the end, we could expect them having more comprehensive actions, and it is also a way to support them. Anyway, ok to use our own actions.
> 
> > I don’t understand what do you mean by "compilation is a bit faster", actions can’t speedup compilations, they’re just javascript scripts executed inside a VM.
> 
> It was probably due to the use of pip in place of conda.

Anything is faster than conda 😬 
For the CI, I use [Micromamba](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html) as a drop-in replacement for conda (and compatible with it). It’s several orders of magnitudes faster.

> > We could preload the conda env as a pre-render project script, but it will need another action script for that: not worth the hassle, IMHO.
> 
> Ok, agree with that. But an example with the possibility of caching the conda-env would be nice. What do you think?

It is already in the CI:
![image](https://user-images.githubusercontent.com/701587/197395384-fa4b973d-0036-42fd-b1bf-a24893a58599.png)

![image](https://user-images.githubusercontent.com/701587/197395488-a6b7fb21-fa67-4d6b-a3f3-10fa4b418d9d.png)

**Comment by jchiquet** [comment]
Ok thanks !
