### ISSUE TITLE
Make a “pure” python/jupyter template

### ISSUE THREAD

**Issue by fradav** [computorg/computo-quarto-extension#5]
As using knitr/reticulate for pure python (or julia for that matter) code cells is not ideal (reticulate is a not completely friction-less experience for using python in R), we should propose a jupyter-engine based format for people not familiar with the R ecosystem (even if they’re very few of them in the stat community we’re coming from, this is not the case for other applied maths communities 😺)

Could we just use the actual format extension and just put another .qmd file there? I don’t think it will be very efficient to maintain two separate extensions.

**Comment by jchiquet** [comment]
Agree.
Note that the mock contribution in the repo https://github.com/computorg/published-paper-tsne only use the Jupyter kernel, but we should do a fully quarto-based jupiter template. At the moment we have a Jupyter Myst template for Python (https://github.com/computorg/template-computo-myst), but it would ease the whole process to encourage users using only quarto-based templates.

**Comment by fradav** [comment]
T-sne paper is in the PR
